run:
  timeout: 5m
  concurrency: 8
  tests: true

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - intrange
    - lll
    - nilerr
    - nilnil
    - predeclared
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
